"""Build the browser's source inventory using only Python's standard library."""

import argparse
import ast
import json
from pathlib import Path


TOOL = Path(__file__).resolve().parent
ROOT = TOOL.parent.parent
OUTPUT = TOOL / "code-index.js"
COMPONENTS = [
    ("simulation_runner", ("simulation_runner/src", "simulation_runner/scripts"), "#73b8f4", "implemented"),
    ("bridge", ("bridge/src",), "#82c6a0", "planned"),
    ("dashboard", ("dashboard/src/afs_dashboard",), "#b69bea", "planned"),
    ("firmware", ("firmware",), "#e7b877", "planned"),
    ("tools", ("tools",), "#dc93ae", "implemented"),
]
EXTENSIONS = {".py", ".js", ".mjs", ".html", ".css", ".c", ".cpp", ".h", ".hpp", ".sh"}
EXCLUDED = {"__pycache__", "node_modules", ".venv", "code-index.js"}


def build_index():
    nodes = [{"id": "repository", "label": "AFS", "parent": None,
              "kind": "repository", "path": ".", "status": "implemented",
              "color": "#d6ddd9", "description": "Adaptive Front-lighting System"}]

    def add(path, parent, color, status, kind, label=None, symbol=None, qualified=None):
        relative = path.relative_to(ROOT).as_posix()
        node_id = relative + (f"#{qualified or symbol.name}" if symbol else "")
        description = ""
        if symbol:
            description = (ast.get_docstring(symbol) or "").split("\n\n", 1)[0]
        node = {"id": node_id, "label": label or path.name, "parent": parent,
                "kind": kind, "path": relative, "status": status, "color": color,
                "description": description}
        if symbol:
            node["line"] = symbol.lineno
        nodes.append(node)
        return node_id

    def walk(directory, parent, color, status):
        for path in sorted(directory.iterdir(), key=lambda p: (not p.is_dir(), p.name)):
            if path.name.startswith(".") or path.name in EXCLUDED or path.is_symlink():
                continue
            child_status = "planned" if path.name == "ipc_adapter" else status
            if path.is_dir():
                before = len(nodes)
                child = add(path, parent, color, child_status, "module")
                walk(path, child, color, child_status)
                # Ignore empty local leftovers, but retain documented scaffold modules.
                if len(nodes) == before + 1 and not (path / "README.md").is_file():
                    nodes.pop()
            elif path.suffix in EXTENSIONS:
                child = add(path, parent, color, status, "file")
                if path.suffix == ".py":
                    tree = ast.parse(path.read_text(encoding="utf-8"))
                    for symbol in tree.body:
                        if not isinstance(symbol, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                            continue
                        # Keep navigation focused on public entry points and selected internal boundaries.
                        if symbol.name.startswith("_") and symbol.name not in {
                            "_write_scene_snapshot", "_clear_scene_snapshot", "_PandaKeyboardInput"
                        }:
                            continue
                        kind = "class" if isinstance(symbol, ast.ClassDef) else "function"
                        symbol_id = add(path, child, color, status, kind, symbol.name, symbol)
                        if isinstance(symbol, ast.ClassDef):
                            for method in symbol.body:
                                if not isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)):
                                    continue
                                if method.name.startswith("_") or method.name == "to_dict":
                                    continue
                                if any(isinstance(decorator, ast.Name) and decorator.id == "property"
                                       for decorator in method.decorator_list):
                                    continue
                                add(path, symbol_id, color, status, "method", method.name,
                                    method, f"{symbol.name}.{method.name}")

    for name, sources, color, status in COMPONENTS:
        component = ROOT / name
        child = add(component, "repository", color, status, "component")
        for source in sources:
            if (ROOT / source).is_dir():
                walk(ROOT / source, child, color, status)
    return nodes


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the saved inventory is stale")
    args = parser.parse_args()
    nodes = build_index()
    content = "// Generated by build_index.py; do not edit.\n"
    content += "globalThis.CODE_INDEX = " + json.dumps(nodes, indent=2, ensure_ascii=False) + ";\n"
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            parser.exit(1, "Code inventory is stale. Run python3 tools/system_visualization/build_index.py\n")
        print(f"Code inventory current: {len(nodes)} nodes.")
    else:
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"Indexed {len(nodes)} nodes into {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
